version: '3.9'

services:
  backend:
    image: backend:1.0
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    tty: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - tour-app

  db:
    image: postgres:13.5
    container_name: backend-db
    ports:
      - "15432:15432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    command: -p 15432
    networks:
      - tour-app
    restart: always

  frontend:
    image: frontend:1.0
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    restart: always
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    networks:
      - tour-app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-webserver
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tour-app
    depends_on:
      - backend


networks:
  tour-app:

volumes:
  postgresql-data:
